# Generated by Django 2.2.5 on 2019-09-22 20:51
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    emit_post_migrate_signal(2, False, 'default')
    content_type = ContentType.objects.get(app_label='blog', model='post')
    permission = Permission.objects.create(codename='can_create_post',
                                           name='Can create post')
    group = Group.objects.filter(name='Authors')
    group.permissions.add(permission)


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions)
    ]
